# Generated by Django 5.0.1 on 2024-06-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
