# Generated by Django 5.0.1 on 2024-06-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_telegramusers_address_alter_telegramusers_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusers',
            name='address',
        ),
    ]
