# Generated by Django 5.0.1 on 2024-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_remove_telegramusers_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
