# Generated by Django 5.0.1 on 2024-06-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0004_telegramusers_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='telegramusers',
            name='district',
        ),
        migrations.RemoveField(
            model_name='telegramusers',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='telegramusers',
            name='longitude',
        ),
    ]
