# Generated by Django 5.0.1 on 2024-08-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0005_remove_telegramusers_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='sell_phone',
            field=models.DateTimeField(null=True),
        ),
    ]
